/*
 * Database OAS
 * Open API Specification REST for FASTEN Holistic Simulator-Optimizer Tool
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: Fasten-wp4@lists.inesctec.pt
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fasten.wp4.database.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasten.wp4.database.client.model.Part;
import com.fasten.wp4.database.client.model.SRAM;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.io.Serializable;

/**
 * Details about producing the part.
 */
@ApiModel(description = "Details about producing the part.")

public class ProcessingPart implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("averagePrintTime")
  private Double averagePrintTime = null;

  @SerializedName("cost")
  private BigDecimal cost = null;

  @SerializedName("estimatedPrintTime")
  private Double estimatedPrintTime = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("lastPrintTime")
  private Double lastPrintTime = null;

  @SerializedName("part")
  private Part part = null;

  @SerializedName("sram")
  private SRAM sram = null;

  public ProcessingPart averagePrintTime(Double averagePrintTime) {
    this.averagePrintTime = averagePrintTime;
    return this;
  }

   /**
   * Get averagePrintTime
   * @return averagePrintTime
  **/
  @ApiModelProperty(value = "")
  public Double getAveragePrintTime() {
    return averagePrintTime;
  }

  public void setAveragePrintTime(Double averagePrintTime) {
    this.averagePrintTime = averagePrintTime;
  }

  public ProcessingPart cost(BigDecimal cost) {
    this.cost = cost;
    return this;
  }

   /**
   * The cost to produce this part in that SRAM (currency)
   * @return cost
  **/
  @ApiModelProperty(value = "The cost to produce this part in that SRAM (currency)")
  public BigDecimal getCost() {
    return cost;
  }

  public void setCost(BigDecimal cost) {
    this.cost = cost;
  }

  public ProcessingPart estimatedPrintTime(Double estimatedPrintTime) {
    this.estimatedPrintTime = estimatedPrintTime;
    return this;
  }

   /**
   * Get estimatedPrintTime
   * @return estimatedPrintTime
  **/
  @ApiModelProperty(value = "")
  public Double getEstimatedPrintTime() {
    return estimatedPrintTime;
  }

  public void setEstimatedPrintTime(Double estimatedPrintTime) {
    this.estimatedPrintTime = estimatedPrintTime;
  }

  public ProcessingPart id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ProcessingPart lastPrintTime(Double lastPrintTime) {
    this.lastPrintTime = lastPrintTime;
    return this;
  }

   /**
   * Get lastPrintTime
   * @return lastPrintTime
  **/
  @ApiModelProperty(value = "")
  public Double getLastPrintTime() {
    return lastPrintTime;
  }

  public void setLastPrintTime(Double lastPrintTime) {
    this.lastPrintTime = lastPrintTime;
  }

  public ProcessingPart part(Part part) {
    this.part = part;
    return this;
  }

   /**
   * The part
   * @return part
  **/
  @ApiModelProperty(value = "The part")
  public Part getPart() {
    return part;
  }

  public void setPart(Part part) {
    this.part = part;
  }

  public ProcessingPart sram(SRAM sram) {
    this.sram = sram;
    return this;
  }

   /**
   * Get sram
   * @return sram
  **/
  @ApiModelProperty(value = "")
  public SRAM getSram() {
    return sram;
  }

  public void setSram(SRAM sram) {
    this.sram = sram;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessingPart processingPart = (ProcessingPart) o;
    return Objects.equals(this.averagePrintTime, processingPart.averagePrintTime) &&
        Objects.equals(this.cost, processingPart.cost) &&
        Objects.equals(this.estimatedPrintTime, processingPart.estimatedPrintTime) &&
        Objects.equals(this.id, processingPart.id) &&
        Objects.equals(this.lastPrintTime, processingPart.lastPrintTime) &&
        Objects.equals(this.part, processingPart.part) &&
        Objects.equals(this.sram, processingPart.sram);
  }

  @Override
  public int hashCode() {
    return Objects.hash(averagePrintTime, cost, estimatedPrintTime, id, lastPrintTime, part, sram);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessingPart {\n");
    
    sb.append("    averagePrintTime: ").append(toIndentedString(averagePrintTime)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    estimatedPrintTime: ").append(toIndentedString(estimatedPrintTime)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastPrintTime: ").append(toIndentedString(lastPrintTime)).append("\n");
    sb.append("    part: ").append(toIndentedString(part)).append("\n");
    sb.append("    sram: ").append(toIndentedString(sram)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

