/*
 * OpenRouteService
 * This is the openrouteservice API V2 documentation for ORS Core-Version `5.0.0`. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor.swagger.io/).
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@openrouteservice.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.ors.matrix.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;
import org.ors.matrix.client.model.EngineInfo;
import org.ors.matrix.client.model.MatrixRequest;
import java.io.Serializable;

/**
 * JSONMatrixResponseMetadata
 */

public class JSONMatrixResponseMetadata implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("attribution")
  private String attribution = null;

  @SerializedName("engine")
  private EngineInfo engine = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("osm_file_md5_hash")
  private String osmFileMd5Hash = null;

  @SerializedName("query")
  private MatrixRequest query = null;

  @SerializedName("timestamp")
  private Date timestamp = null;

  public JSONMatrixResponseMetadata attribution(String attribution) {
    this.attribution = attribution;
    return this;
  }

   /**
   * Copyright and attribution information
   * @return attribution
  **/
  @ApiModelProperty(example = "openrouteservice.org, OpenStreetMap contributors", value = "Copyright and attribution information")
  public String getAttribution() {
    return attribution;
  }

  public void setAttribution(String attribution) {
    this.attribution = attribution;
  }

  public JSONMatrixResponseMetadata engine(EngineInfo engine) {
    this.engine = engine;
    return this;
  }

   /**
   * Get engine
   * @return engine
  **/
  @ApiModelProperty(value = "")
  public EngineInfo getEngine() {
    return engine;
  }

  public void setEngine(EngineInfo engine) {
    this.engine = engine;
  }

  public JSONMatrixResponseMetadata id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID of the request (as passed in by the query)
   * @return id
  **/
  @ApiModelProperty(example = "request123", value = "ID of the request (as passed in by the query)")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public JSONMatrixResponseMetadata osmFileMd5Hash(String osmFileMd5Hash) {
    this.osmFileMd5Hash = osmFileMd5Hash;
    return this;
  }

   /**
   * The MD5 hash of the OSM planet file that was used for generating graphs
   * @return osmFileMd5Hash
  **/
  @ApiModelProperty(example = "c0327ba6", value = "The MD5 hash of the OSM planet file that was used for generating graphs")
  public String getOsmFileMd5Hash() {
    return osmFileMd5Hash;
  }

  public void setOsmFileMd5Hash(String osmFileMd5Hash) {
    this.osmFileMd5Hash = osmFileMd5Hash;
  }

  public JSONMatrixResponseMetadata query(MatrixRequest query) {
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @ApiModelProperty(value = "")
  public MatrixRequest getQuery() {
    return query;
  }

  public void setQuery(MatrixRequest query) {
    this.query = query;
  }

  public JSONMatrixResponseMetadata timestamp(Date timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Timestamp when the query was run
   * @return timestamp
  **/
  @ApiModelProperty(value = "Timestamp when the query was run")
  public Date getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Date timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JSONMatrixResponseMetadata jsONMatrixResponseMetadata = (JSONMatrixResponseMetadata) o;
    return Objects.equals(this.attribution, jsONMatrixResponseMetadata.attribution) &&
        Objects.equals(this.engine, jsONMatrixResponseMetadata.engine) &&
        Objects.equals(this.id, jsONMatrixResponseMetadata.id) &&
        Objects.equals(this.osmFileMd5Hash, jsONMatrixResponseMetadata.osmFileMd5Hash) &&
        Objects.equals(this.query, jsONMatrixResponseMetadata.query) &&
        Objects.equals(this.timestamp, jsONMatrixResponseMetadata.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attribution, engine, id, osmFileMd5Hash, query, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JSONMatrixResponseMetadata {\n");
    
    sb.append("    attribution: ").append(toIndentedString(attribution)).append("\n");
    sb.append("    engine: ").append(toIndentedString(engine)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    osmFileMd5Hash: ").append(toIndentedString(osmFileMd5Hash)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

