/*
 * ngsi-v2
 * NGSI V2 API RC-2018.04
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fasten.wp4.orion.client.api;

import com.fasten.wp4.orion.client.invoker.ApiException;
import com.fasten.wp4.orion.client.model.APIEntryPoint;
import com.fasten.wp4.orion.client.model.ErrorResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiEntryPointApi
 */
@Ignore
public class ApiEntryPointApiTest {

    private final ApiEntryPointApi api = new ApiEntryPointApi();

    
    /**
     * 
     *
     * This resource does not have any attributes. Instead it offers the initial API affordances in the form of the links in the JSON body. It is recommended to follow the “url” link values, [Link](https://tools.ietf.org/html/rfc5988) or Location headers where applicable to retrieve resources. Instead of constructing your own URLs, to keep your client decoupled from implementation details.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveAPIResourcesTest() throws ApiException {
    	try {
		api.getApiClient().setDebugging(true);
        APIEntryPoint response = api.retrieveAPIResources();
        response.getSubscriptionsUrl();
    	}catch(Exception e) {
        	e.printStackTrace();
        }
        // TODO: test validations
    }
    
}
