create table delivery (id  bigserial not null, cost numeric(19, 2), destination_cep varchar(255), distance int4, origin_cep varchar(255), time int4, destination_id int8, origin_id int8, primary key (id));
create table demand (id  bigserial not null, code varchar(255), delivery_date date, order_date date, quantity int4, part_id int8, remote_station_id int8, primary key (id));
create table internal_order (id  bigserial not null, cost numeric(19, 2), part_id int8, remote_station_id int8, primary key (id));
create table internal_supply (id  bigserial not null, part_id int8, remote_station_destination_id int8, remote_station_origin_id int8, primary key (id));
create table optimizator (id  bigserial not null, annual_fixed_cost numeric(19, 2), lead_time_limit float8, number_of_srams int4, primary key (id));
create table part (id  bigserial not null, code varchar(255), depth float8, height float8, name varchar(255), priority varchar(255), width float8, primary key (id));
create table processing_part (id  bigserial not null, avg_producing_time float8, avg_setup_time float8, cost numeric(19, 2), std_producing_time float8, std_setup_time float8, sram_id int8, part_id int8, primary key (id));
create table production (id  bigserial not null, part_id int8, remote_station_id int8, primary key (id));
create table remote_station (id  bigserial not null, city varchar(255), code varchar(255), priority varchar(255), state varchar(255), primary key (id));
create table route (id  bigserial not null, cost numeric(19, 2), lead_time float8, quantity int4, part_id int8, remote_station_destination_id int8, remote_station_origin_id int8, primary key (id));
create table sram (id  bigserial not null, material_available float8, material_in_use float8, volume float8, capacity int4, code varchar(255), humidity float8, temperature float8, fixed_cost numeric(19, 2), process_status varchar(255), status varchar(255), primary key (id));
create table srams_allocated (id  bigserial not null, number_of_srams int4, remote_station_id int8, primary key (id));
create table stock (id  bigserial not null, capital_cost float8, stockout_cost numeric(19, 2), primary key (id));
alter table delivery add constraint FKj7052dwx5uy7ge23334mg9f9f foreign key (destination_id) references remote_station;
alter table delivery add constraint FKk4qqulu2i0ey7i067s1fifan2 foreign key (origin_id) references remote_station;
alter table demand add constraint FK69mk92b6ngcfqig3ex3600bd4 foreign key (part_id) references part;
alter table demand add constraint FKfvpmydh3spw8y1vdeiova4fdl foreign key (remote_station_id) references remote_station;
alter table internal_order add constraint FK840d7tfthgjou3uyk8m6h5lq7 foreign key (part_id) references part;
alter table internal_order add constraint FK7puxd3gv3jfrfewpk01adj2qn foreign key (remote_station_id) references remote_station;
alter table internal_supply add constraint FKr1k2mjv269pw6ds7qdgfje7de foreign key (part_id) references part;
alter table internal_supply add constraint FKeos58s7305gp7rci7hedev4ih foreign key (remote_station_destination_id) references remote_station;
alter table internal_supply add constraint FKbjjw9b49s8h175j3r0kb147sw foreign key (remote_station_origin_id) references remote_station;
alter table processing_part add constraint FKdm89gji6nos5dtgsiymov2y5c foreign key (sram_id) references sram;
alter table processing_part add constraint FKdexvsun9dyw4btvw56r8yefn4 foreign key (part_id) references part;
alter table production add constraint FKmcpnnbx3nomox1lg7m91noovb foreign key (part_id) references part;
alter table production add constraint FKn1b8bbhiebimw0vufju0bo3k2 foreign key (remote_station_id) references remote_station;
alter table route add constraint FKswdj7rufqlnus9d6uxgb5vpkq foreign key (part_id) references part;
alter table route add constraint FK63bafyt3gde94dtxas9vlcrmf foreign key (remote_station_destination_id) references remote_station;
alter table route add constraint FKkx3yfm1tbl30rnyhcc1j63an7 foreign key (remote_station_origin_id) references remote_station;
alter table srams_allocated add constraint FK3kiouldhf1tm8yjj1pu5khhr1 foreign key (remote_station_id) references remote_station;