/*
 * IoT REST OAS
 * Open API Specification REST for IoT event management
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: Fasten-wp4@lists.inesctec.pt
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fasten.wp4.iot.kafka.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;
import java.io.Serializable;

/**
 * HistoricalTimesRequest
 */

public class HistoricalTimesRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("requestedTime")
  private Date requestedTime = null;

  public HistoricalTimesRequest requestedTime(Date requestedTime) {
    this.requestedTime = requestedTime;
    return this;
  }

   /**
   * Get requestedTime
   * @return requestedTime
  **/
  @ApiModelProperty(value = "")
  public Date getRequestedTime() {
    return requestedTime;
  }

  public void setRequestedTime(Date requestedTime) {
    this.requestedTime = requestedTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoricalTimesRequest historicalTimesRequest = (HistoricalTimesRequest) o;
    return Objects.equals(this.requestedTime, historicalTimesRequest.requestedTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestedTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoricalTimesRequest {\n");
    
    sb.append("    requestedTime: ").append(toIndentedString(requestedTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

