/*
 * Allocate Production Order
 * API Description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fasten.wp4.optimizator.operational.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.io.Serializable;

/**
 * AllocationResultInner
 */

public class AllocationResultInner implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("remoteStation")
  private String remoteStation = null;

  @SerializedName("queueTime")
  private BigDecimal queueTime = null;

  @SerializedName("timeProduction")
  private BigDecimal timeProduction = null;

  @SerializedName("timeTravel")
  private BigDecimal timeTravel = null;

  @SerializedName("totalTime")
  private BigDecimal totalTime = null;

  public AllocationResultInner remoteStation(String remoteStation) {
    this.remoteStation = remoteStation;
    return this;
  }

   /**
   * Get remoteStation
   * @return remoteStation
  **/
  @ApiModelProperty(value = "")
  public String getRemoteStation() {
    return remoteStation;
  }

  public void setRemoteStation(String remoteStation) {
    this.remoteStation = remoteStation;
  }

  public AllocationResultInner queueTime(BigDecimal queueTime) {
    this.queueTime = queueTime;
    return this;
  }

   /**
   * Get queueTime
   * @return queueTime
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getQueueTime() {
    return queueTime;
  }

  public void setQueueTime(BigDecimal queueTime) {
    this.queueTime = queueTime;
  }

  public AllocationResultInner timeProduction(BigDecimal timeProduction) {
    this.timeProduction = timeProduction;
    return this;
  }

   /**
   * Get timeProduction
   * @return timeProduction
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getTimeProduction() {
    return timeProduction;
  }

  public void setTimeProduction(BigDecimal timeProduction) {
    this.timeProduction = timeProduction;
  }

  public AllocationResultInner timeTravel(BigDecimal timeTravel) {
    this.timeTravel = timeTravel;
    return this;
  }

   /**
   * Get timeTravel
   * @return timeTravel
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getTimeTravel() {
    return timeTravel;
  }

  public void setTimeTravel(BigDecimal timeTravel) {
    this.timeTravel = timeTravel;
  }

  public AllocationResultInner totalTime(BigDecimal totalTime) {
    this.totalTime = totalTime;
    return this;
  }

   /**
   * Get totalTime
   * @return totalTime
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getTotalTime() {
    return totalTime;
  }

  public void setTotalTime(BigDecimal totalTime) {
    this.totalTime = totalTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllocationResultInner allocationResultInner = (AllocationResultInner) o;
    return Objects.equals(this.remoteStation, allocationResultInner.remoteStation) &&
        Objects.equals(this.queueTime, allocationResultInner.queueTime) &&
        Objects.equals(this.timeProduction, allocationResultInner.timeProduction) &&
        Objects.equals(this.timeTravel, allocationResultInner.timeTravel) &&
        Objects.equals(this.totalTime, allocationResultInner.totalTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(remoteStation, queueTime, timeProduction, timeTravel, totalTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllocationResultInner {\n");
    
    sb.append("    remoteStation: ").append(toIndentedString(remoteStation)).append("\n");
    sb.append("    queueTime: ").append(toIndentedString(queueTime)).append("\n");
    sb.append("    timeProduction: ").append(toIndentedString(timeProduction)).append("\n");
    sb.append("    timeTravel: ").append(toIndentedString(timeTravel)).append("\n");
    sb.append("    totalTime: ").append(toIndentedString(totalTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

