/*
 * IoT REST OAS
 * Open API Specification REST for IoT event management
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: Fasten-wp4@lists.inesctec.pt
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fasten.wp4.iot.kafka.client.api;

import com.fasten.wp4.iot.kafka.client.invoker.ApiException;
import com.fasten.wp4.iot.kafka.client.model.HistoricalDemandRequest;
import com.fasten.wp4.iot.kafka.client.model.HistoricalTimesRequest;
import com.fasten.wp4.iot.kafka.client.model.ProbabilityDistribuitionsRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for KafkaControllerApi
 */
@Ignore
public class KafkaControllerApiTest {

    private final KafkaControllerApi api = new KafkaControllerApi();

    
    /**
     * Fires a event on a Topic
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fireTest() throws ApiException {
        String end = null;
        String start = null;
        String topic = null;
        Object response = api.fire(end, start, topic);

        // TODO: test validations
    }
    
    /**
     * Fires a Historical Demand Request
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHistoricalDemandTest() throws ApiException {
        HistoricalDemandRequest request = null;
        Object response = api.getHistoricalDemand(request);

        // TODO: test validations
    }
    
    /**
     * Fires a Historical Times Request
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHistoricalTimesTest() throws ApiException {
        HistoricalTimesRequest request = null;
        Object response = api.getHistoricalTimes(request);

        // TODO: test validations
    }
    
    /**
     * Fires a Probability Distribuitions Request
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProbabilityDistribuitionsTest() throws ApiException {
        ProbabilityDistribuitionsRequest request = null;
        Object response = api.getProbabilityDistribuitions(request);

        // TODO: test validations
    }
    
}
