/*
 * Email OAS
 * Open API Specification for FASTEN Holistic Simulator-Optimizer Tool
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: fasten.suite@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fasten.wp4.email.client.api;

import com.fasten.wp4.email.client.invoker.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppErrorControllerApi
 */
@Ignore
public class AppErrorControllerApiTest {

    private final AppErrorControllerApi api = new AppErrorControllerApi();

    
    /**
     * error
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorUsingDELETETest() throws ApiException {
        Map<String, Object> response = api.errorUsingDELETE();

        // TODO: test validations
    }
    
    /**
     * error
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorUsingGETTest() throws ApiException {
        Map<String, Object> response = api.errorUsingGET();

        // TODO: test validations
    }
    
    /**
     * error
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorUsingHEADTest() throws ApiException {
        Map<String, Object> response = api.errorUsingHEAD();

        // TODO: test validations
    }
    
    /**
     * error
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorUsingOPTIONSTest() throws ApiException {
        Map<String, Object> response = api.errorUsingOPTIONS();

        // TODO: test validations
    }
    
    /**
     * error
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorUsingPATCHTest() throws ApiException {
        Map<String, Object> response = api.errorUsingPATCH();

        // TODO: test validations
    }
    
    /**
     * error
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorUsingPOSTTest() throws ApiException {
        Map<String, Object> response = api.errorUsingPOST();

        // TODO: test validations
    }
    
    /**
     * error
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorUsingPUTTest() throws ApiException {
        Map<String, Object> response = api.errorUsingPUT();

        // TODO: test validations
    }
    
}
