/*
 * ngsi-v2
 * NGSI V2 API RC-2018.04
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fasten.wp4.orion.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasten.wp4.orion.client.model.QueryPattern;
import com.fasten.wp4.orion.client.model.SubscriptionSubjectConditions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * SubscriptionSubject
 */

public class SubscriptionSubject implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("entities")
  private List<QueryPattern> entities = null;

  @SerializedName("conditions")
  private SubscriptionSubjectConditions conditions = null;

  public SubscriptionSubject entities(List<QueryPattern> entities) {
    this.entities = entities;
    return this;
  }

  public SubscriptionSubject addEntitiesItem(QueryPattern entitiesItem) {
    if (this.entities == null) {
      this.entities = new ArrayList<>();
    }
    this.entities.add(entitiesItem);
    return this;
  }

   /**
   * Get entities
   * @return entities
  **/
  @ApiModelProperty(value = "")
  public List<QueryPattern> getEntities() {
    return entities;
  }

  public void setEntities(List<QueryPattern> entities) {
    this.entities = entities;
  }

  public SubscriptionSubject conditions(SubscriptionSubjectConditions conditions) {
    this.conditions = conditions;
    return this;
  }

   /**
   * Get conditions
   * @return conditions
  **/
  @ApiModelProperty(value = "")
  public SubscriptionSubjectConditions getConditions() {
    return conditions;
  }

  public void setConditions(SubscriptionSubjectConditions conditions) {
    this.conditions = conditions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionSubject subscriptionSubject = (SubscriptionSubject) o;
    return Objects.equals(this.entities, subscriptionSubject.entities) &&
        Objects.equals(this.conditions, subscriptionSubject.conditions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entities, conditions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionSubject {\n");
    
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

