/*
 * Tactical Optimizator OAS
 * Tactical Optimizator Open API Specification REST for FASTEN Holistic Simulator-Optimizer Tool
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: Fasten-wp4@lists.inesctec.pt
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fasten.wp4.optimizator.tactical.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasten.wp4.optimizator.tactical.client.model.CplexResult;
import com.fasten.wp4.optimizator.tactical.client.model.TacticalOptimizationResult;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * TacticalOptimizationResponse
 */

public class TacticalOptimizationResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("cplexResult")
  private CplexResult cplexResult = null;

  @SerializedName("tacticalOptimizationResult")
  private TacticalOptimizationResult tacticalOptimizationResult = null;

  @SerializedName("tacticalOptimizationResults")
  private List<TacticalOptimizationResult> tacticalOptimizationResults = null;

  public TacticalOptimizationResponse cplexResult(CplexResult cplexResult) {
    this.cplexResult = cplexResult;
    return this;
  }

   /**
   * Get cplexResult
   * @return cplexResult
  **/
  @ApiModelProperty(value = "")
  public CplexResult getCplexResult() {
    return cplexResult;
  }

  public void setCplexResult(CplexResult cplexResult) {
    this.cplexResult = cplexResult;
  }

  public TacticalOptimizationResponse tacticalOptimizationResult(TacticalOptimizationResult tacticalOptimizationResult) {
    this.tacticalOptimizationResult = tacticalOptimizationResult;
    return this;
  }

   /**
   * Get tacticalOptimizationResult
   * @return tacticalOptimizationResult
  **/
  @ApiModelProperty(value = "")
  public TacticalOptimizationResult getTacticalOptimizationResult() {
    return tacticalOptimizationResult;
  }

  public void setTacticalOptimizationResult(TacticalOptimizationResult tacticalOptimizationResult) {
    this.tacticalOptimizationResult = tacticalOptimizationResult;
  }

  public TacticalOptimizationResponse tacticalOptimizationResults(List<TacticalOptimizationResult> tacticalOptimizationResults) {
    this.tacticalOptimizationResults = tacticalOptimizationResults;
    return this;
  }

  public TacticalOptimizationResponse addTacticalOptimizationResultsItem(TacticalOptimizationResult tacticalOptimizationResultsItem) {
    if (this.tacticalOptimizationResults == null) {
      this.tacticalOptimizationResults = new ArrayList<>();
    }
    this.tacticalOptimizationResults.add(tacticalOptimizationResultsItem);
    return this;
  }

   /**
   * Get tacticalOptimizationResults
   * @return tacticalOptimizationResults
  **/
  @ApiModelProperty(value = "")
  public List<TacticalOptimizationResult> getTacticalOptimizationResults() {
    return tacticalOptimizationResults;
  }

  public void setTacticalOptimizationResults(List<TacticalOptimizationResult> tacticalOptimizationResults) {
    this.tacticalOptimizationResults = tacticalOptimizationResults;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TacticalOptimizationResponse tacticalOptimizationResponse = (TacticalOptimizationResponse) o;
    return Objects.equals(this.cplexResult, tacticalOptimizationResponse.cplexResult) &&
        Objects.equals(this.tacticalOptimizationResult, tacticalOptimizationResponse.tacticalOptimizationResult) &&
        Objects.equals(this.tacticalOptimizationResults, tacticalOptimizationResponse.tacticalOptimizationResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cplexResult, tacticalOptimizationResult, tacticalOptimizationResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TacticalOptimizationResponse {\n");
    
    sb.append("    cplexResult: ").append(toIndentedString(cplexResult)).append("\n");
    sb.append("    tacticalOptimizationResult: ").append(toIndentedString(tacticalOptimizationResult)).append("\n");
    sb.append("    tacticalOptimizationResults: ").append(toIndentedString(tacticalOptimizationResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

