/*
 * Predictions API by FASTEN
 * Part of Predictive Prescriptive and Analytic Tool.
 *
 * OpenAPI spec version: 1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fasten.wp4.predictive.client.invoker.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
